create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password text not null,
  resume_path text,
  name text,
  birth_date date,
  is_admin boolean default false
);

alter table public.users add column if not exists name text;
alter table public.users add column if not exists birth_date date;
alter table public.users add column if not exists is_admin boolean default false;

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  job_url text not null
);

create unique index if not exists favorites_user_id_job_url_key
  on public.favorites (user_id, job_url);
