CREATE TABLE IF NOT EXISTS api_health (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    api_name TEXT UNIQUE NOT NULL,
    status TEXT NOT NULL,
    latency_ms INTEGER NOT NULL,
    last_check TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
